export interface Surah {
  n: number;
  name: string;
  en: string;
  ayahs: number;
  start: number;
}

export const SURAHS: Surah[] = [
  { n: 1, name: "سُورَةُ ٱلْفَاتِحَةِ", en: "Al-Faatiha", ayahs: 7, start: 1 },
  { n: 2, name: "سُورَةُ البَقَرَةِ", en: "Al-Baqara", ayahs: 286, start: 8 },
  { n: 3, name: "سُورَةُ آلِ عِمۡرَانَ", en: "Aal-i-Imraan", ayahs: 200, start: 294 },
  { n: 4, name: "سُورَةُ النِّسَاءِ", en: "An-Nisaa", ayahs: 176, start: 494 },
  { n: 5, name: "سُورَةُ المَائـِدَةِ", en: "Al-Maaida", ayahs: 120, start: 670 },
  { n: 6, name: "سُورَةُ الأَنۡعَامِ", en: "Al-An'aam", ayahs: 165, start: 790 },
  { n: 7, name: "سُورَةُ الأَعۡرَافِ", en: "Al-A'raaf", ayahs: 206, start: 955 },
  { n: 8, name: "سُورَةُ الأَنفَالِ", en: "Al-Anfaal", ayahs: 75, start: 1161 },
  { n: 9, name: "سُورَةُ التَّوۡبَةِ", en: "At-Tawba", ayahs: 129, start: 1236 },
  { n: 10, name: "سُورَةُ يُونُسَ", en: "Yunus", ayahs: 109, start: 1365 },
  { n: 11, name: "سُورَةُ هُودٍ", en: "Hud", ayahs: 123, start: 1474 },
  { n: 12, name: "سُورَةُ يُوسُفَ", en: "Yusuf", ayahs: 111, start: 1597 },
  { n: 13, name: "سُورَةُ الرَّعۡدِ", en: "Ar-Ra'd", ayahs: 43, start: 1708 },
  { n: 14, name: "سُورَةُ إِبۡرَاهِيمَ", en: "Ibrahim", ayahs: 52, start: 1751 },
  { n: 15, name: "سُورَةُ الحِجۡرِ", en: "Al-Hijr", ayahs: 99, start: 1803 },
  { n: 16, name: "سُورَةُ النَّحۡلِ", en: "An-Nahl", ayahs: 128, start: 1902 },
  { n: 17, name: "سُورَةُ الإِسۡرَاءِ", en: "Al-Israa", ayahs: 111, start: 2030 },
  { n: 18, name: "سُورَةُ الكَهۡفِ", en: "Al-Kahf", ayahs: 110, start: 2141 },
  { n: 19, name: "سُورَةُ مَرۡيَمَ", en: "Maryam", ayahs: 98, start: 2251 },
  { n: 20, name: "سُورَةُ طه", en: "Taa-Haa", ayahs: 135, start: 2349 },
  { n: 21, name: "سُورَةُ الأَنبِيَاءِ", en: "Al-Anbiyaa", ayahs: 112, start: 2484 },
  { n: 22, name: "سُورَةُ الحَجِّ", en: "Al-Hajj", ayahs: 78, start: 2596 },
  { n: 23, name: "سُورَةُ المُؤۡمِنُونَ", en: "Al-Muminoon", ayahs: 118, start: 2674 },
  { n: 24, name: "سُورَةُ النُّورِ", en: "An-Noor", ayahs: 64, start: 2792 },
  { n: 25, name: "سُورَةُ الفُرۡقَانِ", en: "Al-Furqaan", ayahs: 77, start: 2856 },
  { n: 26, name: "سُورَةُ الشُّعَرَاءِ", en: "Ash-Shu'araa", ayahs: 227, start: 2933 },
  { n: 27, name: "سُورَةُ النَّمۡلِ", en: "An-Naml", ayahs: 93, start: 3160 },
  { n: 28, name: "سُورَةُ القَصَصِ", en: "Al-Qasas", ayahs: 88, start: 3253 },
  { n: 29, name: "سُورَةُ العَنكَبُوتِ", en: "Al-Ankaboot", ayahs: 69, start: 3341 },
  { n: 30, name: "سُورَةُ الرُّومِ", en: "Ar-Room", ayahs: 60, start: 3410 },
  { n: 31, name: "سُورَةُ لُقۡمَانَ", en: "Luqman", ayahs: 34, start: 3470 },
  { n: 32, name: "سُورَةُ السَّجۡدَةِ", en: "As-Sajda", ayahs: 30, start: 3504 },
  { n: 33, name: "سُورَةُ الأَحۡزَابِ", en: "Al-Ahzaab", ayahs: 73, start: 3534 },
  { n: 34, name: "سُورَةُ سَبَإٍ", en: "Saba", ayahs: 54, start: 3607 },
  { n: 35, name: "سُورَةُ فَاطِرٍ", en: "Faatir", ayahs: 45, start: 3661 },
  { n: 36, name: "سُورَةُ يسٓ", en: "Yaseen", ayahs: 83, start: 3706 },
  { n: 37, name: "سُورَةُ الصَّافَّاتِ", en: "As-Saaffaat", ayahs: 182, start: 3789 },
  { n: 38, name: "سُورَةُ صٓ", en: "Saad", ayahs: 88, start: 3971 },
  { n: 39, name: "سُورَةُ الزُّمَرِ", en: "Az-Zumar", ayahs: 75, start: 4059 },
  { n: 40, name: "سُورَةُ غَافِرٍ", en: "Ghafir", ayahs: 85, start: 4134 },
  { n: 41, name: "سُورَةُ فُصِّلَتۡ", en: "Fussilat", ayahs: 54, start: 4219 },
  { n: 42, name: "سُورَةُ الشُّورَىٰ", en: "Ash-Shura", ayahs: 53, start: 4273 },
  { n: 43, name: "سُورَةُ الزُّخۡرُفِ", en: "Az-Zukhruf", ayahs: 89, start: 4326 },
  { n: 44, name: "سُورَةُ الدُّخَانِ", en: "Ad-Dukhaan", ayahs: 59, start: 4415 },
  { n: 45, name: "سُورَةُ الجَاثِيَةِ", en: "Al-Jaathiya", ayahs: 37, start: 4474 },
  { n: 46, name: "سُورَةُ الأَحۡقَافِ", en: "Al-Ahqaf", ayahs: 35, start: 4511 },
  { n: 47, name: "سُورَةُ مُحَمَّدٍ", en: "Muhammad", ayahs: 38, start: 4546 },
  { n: 48, name: "سُورَةُ الفَتۡحِ", en: "Al-Fath", ayahs: 29, start: 4584 },
  { n: 49, name: "سُورَةُ الحُجُرَاتِ", en: "Al-Hujuraat", ayahs: 18, start: 4613 },
  { n: 50, name: "سُورَةُ قٓ", en: "Qaaf", ayahs: 45, start: 4631 },
  { n: 51, name: "سُورَةُ الذَّارِيَاتِ", en: "Adh-Dhaariyat", ayahs: 60, start: 4676 },
  { n: 52, name: "سُورَةُ الطُّورِ", en: "At-Tur", ayahs: 49, start: 4736 },
  { n: 53, name: "سُورَةُ النَّجۡمِ", en: "An-Najm", ayahs: 62, start: 4785 },
  { n: 54, name: "سُورَةُ القَمَرِ", en: "Al-Qamar", ayahs: 55, start: 4847 },
  { n: 55, name: "سُورَةُ الرَّحۡمَٰن", en: "Ar-Rahmaan", ayahs: 78, start: 4902 },
  { n: 56, name: "سُورَةُ الوَاقِعَةِ", en: "Al-Waaqia", ayahs: 96, start: 4980 },
  { n: 57, name: "سُورَةُ الحَدِيدِ", en: "Al-Hadid", ayahs: 29, start: 5076 },
  { n: 58, name: "سُورَةُ المُجَادلَةِ", en: "Al-Mujaadila", ayahs: 22, start: 5105 },
  { n: 59, name: "سُورَةُ الحَشۡرِ", en: "Al-Hashr", ayahs: 24, start: 5127 },
  { n: 60, name: "سُورَةُ المُمۡتَحنَةِ", en: "Al-Mumtahana", ayahs: 13, start: 5151 },
  { n: 61, name: "سُورَةُ الصَّفِّ", en: "As-Saff", ayahs: 14, start: 5164 },
  { n: 62, name: "سُورَةُ الجُمُعَةِ", en: "Al-Jumu'a", ayahs: 11, start: 5178 },
  { n: 63, name: "سُورَةُ المُنَافِقُونَ", en: "Al-Munaafiqoon", ayahs: 11, start: 5189 },
  { n: 64, name: "سُورَةُ التَّغَابُنِ", en: "At-Taghaabun", ayahs: 18, start: 5200 },
  { n: 65, name: "سُورَةُ الطَّلَاقِ", en: "At-Talaaq", ayahs: 12, start: 5218 },
  { n: 66, name: "سُورَةُ التَّحۡرِيمِ", en: "At-Tahrim", ayahs: 12, start: 5230 },
  { n: 67, name: "سُورَةُ المُلۡكِ", en: "Al-Mulk", ayahs: 30, start: 5242 },
  { n: 68, name: "سُورَةُ القَلَمِ", en: "Al-Qalam", ayahs: 52, start: 5272 },
  { n: 69, name: "سُورَةُ الحَاقَّةِ", en: "Al-Haaqqa", ayahs: 52, start: 5324 },
  { n: 70, name: "سُورَةُ المَعَارِجِ", en: "Al-Ma'aarij", ayahs: 44, start: 5376 },
  { n: 71, name: "سُورَةُ نُوحٍ", en: "Nooh", ayahs: 28, start: 5420 },
  { n: 72, name: "سُورَةُ الجِنِّ", en: "Al-Jinn", ayahs: 28, start: 5448 },
  { n: 73, name: "سُورَةُ المُزَّمِّلِ", en: "Al-Muzzammil", ayahs: 20, start: 5476 },
  { n: 74, name: "سُورَةُ المُدَّثِّرِ", en: "Al-Muddaththir", ayahs: 56, start: 5496 },
  { n: 75, name: "سُورَةُ القِيَامَةِ", en: "Al-Qiyaama", ayahs: 40, start: 5552 },
  { n: 76, name: "سُورَةُ الإِنسَانِ", en: "Al-Insaan", ayahs: 31, start: 5592 },
  { n: 77, name: "سُورَةُ المُرۡسَلَاتِ", en: "Al-Mursalaat", ayahs: 50, start: 5623 },
  { n: 78, name: "سُورَةُ النَّبَإِ", en: "An-Naba", ayahs: 40, start: 5673 },
  { n: 79, name: "سُورَةُ النَّازِعَاتِ", en: "An-Naazi'aat", ayahs: 46, start: 5713 },
  { n: 80, name: "سُورَةُ عَبَسَ", en: "Abasa", ayahs: 42, start: 5759 },
  { n: 81, name: "سُورَةُ التَّكۡوِيرِ", en: "At-Takwir", ayahs: 29, start: 5801 },
  { n: 82, name: "سُورَةُ الانفِطَارِ", en: "Al-Infitaar", ayahs: 19, start: 5830 },
  { n: 83, name: "سُورَةُ المُطَفِّفِينَ", en: "Al-Mutaffifin", ayahs: 36, start: 5849 },
  { n: 84, name: "سُورَةُ الانشِقَاقِ", en: "Al-Inshiqaaq", ayahs: 25, start: 5885 },
  { n: 85, name: "سُورَةُ البُرُوجِ", en: "Al-Burooj", ayahs: 22, start: 5910 },
  { n: 86, name: "سُورَةُ الطَّارِقِ", en: "At-Taariq", ayahs: 17, start: 5932 },
  { n: 87, name: "سُورَةُ الأَعۡلَىٰ", en: "Al-A'laa", ayahs: 19, start: 5949 },
  { n: 88, name: "سُورَةُ الغَاشِيَةِ", en: "Al-Ghaashiya", ayahs: 26, start: 5968 },
  { n: 89, name: "سُورَةُ الفَجۡرِ", en: "Al-Fajr", ayahs: 30, start: 5994 },
  { n: 90, name: "سُورَةُ البَلَدِ", en: "Al-Balad", ayahs: 20, start: 6024 },
  { n: 91, name: "سُورَةُ الشَّمۡسِ", en: "Ash-Shams", ayahs: 15, start: 6044 },
  { n: 92, name: "سُورَةُ اللَّيۡلِ", en: "Al-Lail", ayahs: 21, start: 6059 },
  { n: 93, name: "سُورَةُ الضُّحَىٰ", en: "Ad-Dhuhaa", ayahs: 11, start: 6080 },
  { n: 94, name: "سُورَةُ الشَّرۡحِ", en: "Ash-Sharh", ayahs: 8, start: 6091 },
  { n: 95, name: "سُورَةُ التِّينِ", en: "At-Tin", ayahs: 8, start: 6099 },
  { n: 96, name: "سُورَةُ العَلَقِ", en: "Al-Alaq", ayahs: 19, start: 6107 },
  { n: 97, name: "سُورَةُ القَدۡرِ", en: "Al-Qadr", ayahs: 5, start: 6126 },
  { n: 98, name: "سُورَةُ البَيِّنَةِ", en: "Al-Bayyina", ayahs: 8, start: 6131 },
  { n: 99, name: "سُورَةُ الزَّلۡزَلَةِ", en: "Az-Zalzala", ayahs: 8, start: 6139 },
  { n: 100, name: "سُورَةُ العَادِيَاتِ", en: "Al-Aadiyaat", ayahs: 11, start: 6147 },
  { n: 101, name: "سُورَةُ القَارِعَةِ", en: "Al-Qaari'a", ayahs: 11, start: 6158 },
  { n: 102, name: "سُورَةُ التَّكَاثُرِ", en: "At-Takaathur", ayahs: 8, start: 6169 },
  { n: 103, name: "سُورَةُ العَصۡرِ", en: "Al-Asr", ayahs: 3, start: 6177 },
  { n: 104, name: "سُورَةُ الهُمَزَةِ", en: "Al-Humaza", ayahs: 9, start: 6180 },
  { n: 105, name: "سُورَةُ الفِيلِ", en: "Al-Fil", ayahs: 5, start: 6189 },
  { n: 106, name: "سُورَةُ قُرَيۡشٍ", en: "Quraish", ayahs: 4, start: 6194 },
  { n: 107, name: "سُورَةُ المَاعُونِ", en: "Al-Maa'un", ayahs: 7, start: 6198 },
  { n: 108, name: "سُورَةُ الكَوۡثَرِ", en: "Al-Kawthar", ayahs: 3, start: 6205 },
  { n: 109, name: "سُورَةُ الكَافِرُونَ", en: "Al-Kaafiroon", ayahs: 6, start: 6208 },
  { n: 110, name: "سُورَةُ النَّصۡرِ", en: "An-Nasr", ayahs: 3, start: 6214 },
  { n: 111, name: "سُورَةُ المَسَدِ", en: "Al-Masad", ayahs: 5, start: 6217 },
  { n: 112, name: "سُورَةُ الإِخۡلَاصِ", en: "Al-Ikhlaas", ayahs: 4, start: 6222 },
  { n: 113, name: "سُورَةُ الفَلَقِ", en: "Al-Falaq", ayahs: 5, start: 6226 },
  { n: 114, name: "سُورَةُ النَّاسِ", en: "An-Naas", ayahs: 6, start: 6231 },
];

export const TOTAL_AYAHS = 6236;

